[package]
name = "pstor-usage"
description = "Persistent Storage Usage"
version = "0.1.0"
edition = "2018"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
openapi = { path = "../../openapi", default-features = false, features = [ "tower-client", "tower-trace" ] }
deployer-cluster = { path = "../../utils/deployer-cluster" }
utils = { path = "../utils-lib" }
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["color", "derive", "env", "string"] }
parse-size = { version = "1.0.0", features = [ "std" ] }
async-trait = "0.1.64"
etcd-client = "0.10.2"
prettytable-rs = "0.10.0"
serde = "1.0.152"
serde_yaml = "0.9.17"
itertools = "0.10.5"


